(()=>{"use strict";
const ACCESS_CODE="MARCELLO-RH-2026";
const CHAIN={chainId:"0xb626",chainName:"Robinhood Chain Testnet",nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:["https://rpc.testnet.chain.robinhood.com/"],blockExplorerUrls:["https://explorer.testnet.chain.robinhood.com"]};
const $=id=>document.getElementById(id); let account=null;
function unlock(){sessionStorage.setItem("ma_launch_access","1");$("accessGate").hidden=true;$("launchApp").hidden=false}
if(sessionStorage.getItem("ma_launch_access")==="1") unlock();
$("accessForm").addEventListener("submit",e=>{e.preventDefault();const ok=$("accessCode").value.trim()===ACCESS_CODE;$("accessError").hidden=ok;if(ok)unlock()});
$("lockBtn").onclick=()=>{sessionStorage.removeItem("ma_launch_access");location.reload()};
let activeProvider=null;
function providers(){const out=[];const add=p=>{if(p&&typeof p.request==="function"&&!out.includes(p))out.push(p)};add(window.ethereum);if(window.ethereum&&Array.isArray(window.ethereum.providers))window.ethereum.providers.forEach(add);add(window.okxwallet);add(window.okxwallet&&window.okxwallet.ethereum);add(window.coinbaseWalletExtension);return out}
function chooseProvider(kind){const ps=providers();if(kind==="metamask"){const direct=window.ethereum&&window.ethereum.isMetaMask&&!window.ethereum.isOkxWallet&&!window.ethereum.isOKExWallet?window.ethereum:null;return ps.find(p=>p.isMetaMask&&!p.isOkxWallet&&!p.isOKExWallet)||direct}if(kind==="okx"){return (window.okxwallet&&window.okxwallet.ethereum)||window.okxwallet||ps.find(p=>p.isOkxWallet||p.isOKExWallet)||null}return ps.find(p=>!p.isMetaMask&&!p.isOkxWallet&&!p.isOKExWallet)||ps[0]||null}
function walletMatches(p,kind){if(kind==="metamask")return !!(p&&p.isMetaMask&&!p.isOkxWallet&&!p.isOKExWallet);if(kind==="okx")return !!(p&&(p.isOkxWallet||p.isOKExWallet||p===(window.okxwallet&&window.okxwallet.ethereum)||p===window.okxwallet));return !!p}
async function ensureNetwork(p=activeProvider){try{await p.request({method:"wallet_switchEthereumChain",params:[{chainId:CHAIN.chainId}]})}catch(e){if(e.code===4902||e.code===-32603){await p.request({method:"wallet_addEthereumChain",params:[CHAIN]})}else throw e}}
$("connectWallet").onclick=()=>{$("walletPicker").hidden=false};
$("closeWalletPicker").onclick=()=>{$("walletPicker").hidden=true};
document.querySelectorAll(".wallet-option").forEach(btn=>btn.onclick=async()=>{const kind=btn.dataset.wallet,p=chooseProvider(kind);if(!p){if(kind==="metamask")window.open("https://metamask.io/download/","_blank");else if(kind==="okx")window.open("https://web3.okx.com/download","_blank");else alert("Wallet EVM tidak terdeteksi di browser ini.");return}try{if(!walletMatches(p,kind)&&kind!=="injected")throw new Error("Provider "+kind+" tidak cocok dengan wallet yang dipilih.");activeProvider=p;const a=await p.request({method:"eth_requestAccounts"});account=a[0];await ensureNetwork(p);$("walletPicker").hidden=true;$("walletState").textContent="Connected";$("walletState").classList.add("is-ok");$("walletInfo").hidden=false;$("walletAddress").textContent=account;$("connectWallet").textContent=(kind==="okx"?"OKX":kind==="metamask"?"MetaMask":"Wallet")+" Connected";$("deployToken").disabled=false;$("deployToken").textContent="Deploy Token on Testnet →"}catch(e){alert(e.message||"Wallet connection failed")}});

const source=(name,symbol)=>`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
contract MarcelloFixedERC20 {
string public name; string public symbol; uint8 public constant decimals=18; uint256 public totalSupply;
mapping(address=>uint256) public balanceOf; mapping(address=>mapping(address=>uint256)) public allowance;
event Transfer(address indexed from,address indexed to,uint256 value); event Approval(address indexed owner,address indexed spender,uint256 value);
constructor(string memory n,string memory s,uint256 supply,address owner){name=n;symbol=s;totalSupply=supply;balanceOf[owner]=supply;emit Transfer(address(0),owner,supply);}
function transfer(address to,uint256 v) external returns(bool){require(balanceOf[msg.sender]>=v,"balance");unchecked{balanceOf[msg.sender]-=v;}balanceOf[to]+=v;emit Transfer(msg.sender,to,v);return true;}
function approve(address s,uint256 v) external returns(bool){allowance[msg.sender][s]=v;emit Approval(msg.sender,s,v);return true;}
function transferFrom(address f,address t,uint256 v) external returns(bool){require(balanceOf[f]>=v,"balance");uint256 a=allowance[f][msg.sender];require(a>=v,"allowance");if(a!=type(uint256).max)allowance[f][msg.sender]=a-v;unchecked{balanceOf[f]-=v;}balanceOf[t]+=v;emit Transfer(f,t,v);return true;}
}`;
function compile(name,symbol){if(typeof Module==="undefined")throw new Error("Solidity compiler belum termuat. Refresh halaman dan coba lagi.");const solc=solcWrapper(Module);const input={language:"Solidity",sources:{"Token.sol":{content:source(name,symbol)}},settings:{optimizer:{enabled:true,runs:200},outputSelection:{"*":{"*":["abi","evm.bytecode.object"]}}}};const out=JSON.parse(solc.compile(JSON.stringify(input)));if(out.errors){const fatal=out.errors.filter(x=>x.severity==="error");if(fatal.length)throw new Error(fatal.map(x=>x.formattedMessage).join("\n"))}return out.contracts["Token.sol"].MarcelloFixedERC20}
function solcWrapper(Module){const compileStandard=Module.cwrap("solidity_compile","string",["string","number","number"]);return{compile:input=>compileStandard(input,0,0)}}
$("tokenForm").addEventListener("submit",async e=>{e.preventDefault();if(!account||!window.ethereum)return;const name=$("tokenName").value.trim(),symbol=$("tokenSymbol").value.trim().toUpperCase(),raw=$("tokenSupply").value.trim();if(!name||!symbol||!/^\d+$/.test(raw)){alert("Periksa kembali data token.");return}try{await ensureNetwork();$("launchProgress").hidden=false;$("launchSuccess").hidden=true;$("progressTitle").textContent="Compiling ERC-20…";$("progressText").textContent="Menyiapkan fixed-supply contract di browser Anda.";await new Promise(r=>setTimeout(r,50));const c=compile(name,symbol);const provider=new ethers.BrowserProvider(activeProvider||window.ethereum);const signer=await provider.getSigner();const supply=ethers.parseUnits(raw,18);const factory=new ethers.ContractFactory(c.abi,"0x"+c.evm.bytecode.object,signer);$("progressTitle").textContent="Confirm deployment in wallet";$("progressText").textContent="Periksa estimasi gas dan konfirmasi transaksi testnet.";const contract=await factory.deploy(name,symbol,supply,account);$("progressTitle").textContent="Waiting for confirmation…";await contract.waitForDeployment();const addr=await contract.getAddress();$("launchProgress").hidden=true;$("launchSuccess").hidden=false;$("contractAddress").textContent=addr;$("explorerLink").href=CHAIN.blockExplorerUrls[0]+"/address/"+addr;$("copyAddress").onclick=()=>navigator.clipboard.writeText(addr);$("launchSuccess").scrollIntoView({behavior:"smooth"})}catch(err){$("launchProgress").hidden=true;alert(err.shortMessage||err.message||"Deployment failed")}});})();