(()=>{"use strict";
const ACCESS_HASH="83b74934659cf63aec60e5c1b6a29fe97f22629c85a3b2548d39dddb552fd479";
const CHAIN={chainId:"0xb626",chainName:"Robinhood Chain Testnet",nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:["https://rpc.testnet.chain.robinhood.com"],blockExplorerUrls:["https://explorer.testnet.chain.robinhood.com"]};
const $=id=>document.getElementById(id); let account=null;
async function sha256(v){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function unlock(){sessionStorage.setItem("ma_launch_access","1");$("accessGate").hidden=true;$("launchApp").hidden=false}
if(sessionStorage.getItem("ma_launch_access")==="1") unlock();
$("accessForm").addEventListener("submit",async e=>{e.preventDefault();const ok=await sha256($("accessCode").value.trim())===ACCESS_HASH;$("accessError").hidden=ok;if(ok)unlock()});
$("lockBtn").onclick=()=>{sessionStorage.removeItem("ma_launch_access");location.reload()};
async function ensureNetwork(){try{await ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:CHAIN.chainId}]})}catch(e){if(e.code===4902){await ethereum.request({method:"wallet_addEthereumChain",params:[CHAIN]})}else throw e}}
$("connectWallet").onclick=async()=>{if(!window.ethereum){alert("Browser wallet EVM tidak ditemukan. Buka halaman ini melalui browser yang memiliki MetaMask atau wallet kompatibel.");return}try{await ensureNetwork();const a=await ethereum.request({method:"eth_requestAccounts"});account=a[0];$("walletState").textContent="Connected";$("walletState").classList.add("is-ok");$("walletInfo").hidden=false;$("walletAddress").textContent=account;$("connectWallet").textContent="Wallet Connected";$("deployToken").disabled=false;$("deployToken").textContent="Deploy Token on Testnet →"}catch(e){alert(e.message||"Wallet connection failed")}};
const source=(name,symbol)=>`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
contract MarcelloFixedERC20 {
string public name; string public symbol; uint8 public constant decimals=18; uint256 public totalSupply;
mapping(address=>uint256) public balanceOf; mapping(address=>mapping(address=>uint256)) public allowance;
event Transfer(address indexed from,address indexed to,uint256 value); event Approval(address indexed owner,address indexed spender,uint256 value);
constructor(string memory n,string memory s,uint256 supply,address owner){name=n;symbol=s;totalSupply=supply;balanceOf[owner]=supply;emit Transfer(address(0),owner,supply);}
function transfer(address to,uint256 v) external returns(bool){require(balanceOf[msg.sender]>=v,"balance");unchecked{balanceOf[msg.sender]-=v;}balanceOf[to]+=v;emit Transfer(msg.sender,to,v);return true;}
function approve(address s,uint256 v) external returns(bool){allowance[msg.sender][s]=v;emit Approval(msg.sender,s,v);return true;}
function transferFrom(address f,address t,uint256 v) external returns(bool){require(balanceOf[f]>=v,"balance");uint256 a=allowance[f][msg.sender];require(a>=v,"allowance");if(a!=type(uint256).max)allowance[f][msg.sender]=a-v;unchecked{balanceOf[f]-=v;}balanceOf[t]+=v;emit Transfer(f,t,v);return true;}
}`;
function compile(name,symbol){if(typeof Module==="undefined")throw new Error("Solidity compiler belum termuat. Refresh halaman dan coba lagi.");const solc=solcWrapper(Module);const input={language:"Solidity",sources:{"Token.sol":{content:source(name,symbol)}},settings:{optimizer:{enabled:true,runs:200},outputSelection:{"*":{"*":["abi","evm.bytecode.object"]}}}};const out=JSON.parse(solc.compile(JSON.stringify(input)));if(out.errors){const fatal=out.errors.filter(x=>x.severity==="error");if(fatal.length)throw new Error(fatal.map(x=>x.formattedMessage).join("\n"))}return out.contracts["Token.sol"].MarcelloFixedERC20}
function solcWrapper(Module){const compileStandard=Module.cwrap("solidity_compile","string",["string","number","number"]);return{compile:input=>compileStandard(input,0,0)}}
$("tokenForm").addEventListener("submit",async e=>{e.preventDefault();if(!account||!window.ethereum)return;const name=$("tokenName").value.trim(),symbol=$("tokenSymbol").value.trim().toUpperCase(),raw=$("tokenSupply").value.trim();if(!name||!symbol||!/^\d+$/.test(raw)){alert("Periksa kembali data token.");return}try{await ensureNetwork();$("launchProgress").hidden=false;$("launchSuccess").hidden=true;$("progressTitle").textContent="Compiling ERC-20…";$("progressText").textContent="Menyiapkan fixed-supply contract di browser Anda.";await new Promise(r=>setTimeout(r,50));const c=compile(name,symbol);const provider=new ethers.BrowserProvider(window.ethereum);const signer=await provider.getSigner();const supply=ethers.parseUnits(raw,18);const factory=new ethers.ContractFactory(c.abi,"0x"+c.evm.bytecode.object,signer);$("progressTitle").textContent="Confirm deployment in wallet";$("progressText").textContent="Periksa estimasi gas dan konfirmasi transaksi testnet.";const contract=await factory.deploy(name,symbol,supply,account);$("progressTitle").textContent="Waiting for confirmation…";await contract.waitForDeployment();const addr=await contract.getAddress();$("launchProgress").hidden=true;$("launchSuccess").hidden=false;$("contractAddress").textContent=addr;$("explorerLink").href=CHAIN.blockExplorerUrls[0]+"/address/"+addr;$("copyAddress").onclick=()=>navigator.clipboard.writeText(addr);$("launchSuccess").scrollIntoView({behavior:"smooth"})}catch(err){$("launchProgress").hidden=true;alert(err.shortMessage||err.message||"Deployment failed")}});})();